apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-backend-app
  namespace: api
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: django-backend-app
  template:
    metadata:
      labels:
        app: django-backend-app
    spec:
      containers:
      - name: django-backend-app
        image: username/clock:81750055651bbe6db78ac1828abd43144f08213e
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8000
          hostPort: 80
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 80
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/health
            port: liveness-port
          initialDelaySeconds: 80
          periodSeconds: 3
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: django-backend-secret
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: django-backend-secret
                key: DB_USER
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: django-backend-secret
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: django-backend-secret
                key: DB_PASS
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: django-backend-secret
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: django-backend-secret
                key: DB_NAME
      imagePullSecrets:
      - name: dockercreds
