apiVersion: v1
kind: Secret
metadata:
  name: django-backend-secret
  namespace: api
type: Opaque
data:
  DB_HOST: RDS_URL
  DB_USER: cG9zdGdyZXM=
  DB_PASS: cm9vdHJvb3Q=
  DB_PORT: NTQzMg==
  DB_NAME: cmVjaXBl
