apiVersion: batch/v1
kind: Job
metadata:
  name: django-backend
  namespace: api
spec:
  template:
    spec:
      containers:
      - name: django-backend-app
        image: hemalgadhiya/csye-7374-advanced-cloud-webapp-backend:d455cdfa567cfcd7bd5eca40c1926b1a850c3a59
        command: ["python",  "./recipe_management/manage.py", "migrate"]
        envFrom:
          - configMapRef:
              name: configmap
      imagePullSecrets:
        - name: dockercreds
      restartPolicy: Never
  backoffLimit: 4
