apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-backend
  namespace: api
  labels:
    app: django-backend

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: django-backend

  template:
    metadata:
      labels:
        app: django-backend

    spec:
      containers:
      - name: django-backend-app
        image: hemalgadhiya/csye-7374-advanced-cloud-webapp-backend:f5635ac5114a61b2b4477d6df5e3962975ec2516
#        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 8080
        envFrom:
        - configMapRef:
           name: configmap
      imagePullSecrets:
      - name: dockercreds
