apiVersion: v1
kind: Service
metadata:
  name: django-backend-app
  namespace: api
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: django-backend
  type: LoadBalancer
