apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-backend-app
  namespace: api
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: django-backend-app
  template:
    metadata:
      labels:
        app: django-backend-app
    spec:
      containers:
      - name: django-backend-app
        image: hemalgadhiya/csye-7374-advanced-cloud-webapp-backend:e727b63194337deddd4d1a63e08e0431cb4eb274
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 8000
        envFrom:
        - configMapRef:
           name: configmap
      imagePullSecrets:
      - name: dockercreds
