apiVersion: batch/v1
kind: Job
metadata:
  name: django-backend
  namespace: api
spec:
  template:
    spec:
      containers:
      - name: django-backend-app
        image: hemalgadhiya/csye-7374-advanced-cloud-webapp-backend:a787201fdedc53818f67ec5bb1ad96e2fe7635e6
        command: ["python",  "manage.py", "migrate"]
        envFrom:
          - configMapRef:
              name: configmap
      imagePullSecrets:
        - name: dockercreds
      restartPolicy: Never
  backoffLimit: 4
