apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: django-backend-app
  namespace: api
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /v1/user
          backend:
            serviceName: django-backend
            servicePort: 8080
        - path: /v1/recipe/
          backend:
            serviceName: django-backend
            servicePort: 8080
