apiVersion: v1
kind: Secret
metadata:
  name: django-backend-secret
  namespace: api
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtcmRzLWluc3RhbmNlLmN3cHFqZGRnOHFyci51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_USER: cG9zdGdyZXM=
  DB_PASS: cm9vdHJvb3Q=
  DB_PORT: NTQzMg==
  DB_NAME: cmVjaXBl
