apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: django-backend-app
  namespace: api
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: django-backend-app
  template:
    metadata:
      labels:
        app: django-backend-app
    spec:
      containers:
      - name: django-backend-app
        image: username/image:81750055651bbe6db78ac1828abd43144f08213e
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 8000
        envFrom:
        - configMapRef:
           name: configmap
      imagePullSecrets:
      - name: dockercreds
