apiVersion: batch/v1
kind: Job
metadata:
  name: django-backend
  namespace: api
spec:
  template:
    spec:
      containers:
      - name: django-backend-app
        image: hemalgadhiya/csye-7374-advanced-cloud-webapp-backend:f5635ac5114a61b2b4477d6df5e3962975ec2516
        command: ["python", "manage.py", "makemigrations", "recipes"]
        envFrom:
          - configMapRef:
              name: configmap
      restartPolicy: Never
  backoffLimit: 4
